/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_lab;

import java.util.Arrays;
import javax.swing.JButton;

/**
 *
 * @author Carlos Nuila
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    JButton[][] tablero = new JButton[8][8];
    String[][] tableroString = new String[8][8];
    Pieza peon1 = new Peon(1);
    Pieza peon2 = new Peon(2);
    Pieza torre1 = new Torre(1);
    Pieza torre2 = new Torre(2);
    Pieza caballo1 = new Caballo(1);
    Pieza caballo2 = new Caballo(2);
    Pieza rey1 = new Rey(1);
    Pieza rey2 = new Rey(2);
    Pieza reina1 = new Reina(1);
    Pieza reina2 = new Reina(2);
    Pieza alfil1 = new Alfil(1);
    Pieza alfil2 = new Alfil(2);

    JButton posActual = new JButton();
    JButton posDestino = new JButton();

    int turno = 1;
    int flag = 0;

    public Interfaz() {
        initComponents();

        tablero[0][0] = jb_00;
        tablero[0][1] = jb_01;
        tablero[0][2] = jb_02;
        tablero[0][3] = jb_03;
        tablero[0][4] = jb_04;
        tablero[0][5] = jb_05;
        tablero[0][6] = jb_06;
        tablero[0][7] = jb_07;
        tablero[1][0] = jb_10;
        tablero[1][1] = jb_11;
        tablero[1][2] = jb_12;
        tablero[1][3] = jb_13;
        tablero[1][4] = jb_14;
        tablero[1][5] = jb_15;
        tablero[1][6] = jb_16;
        tablero[1][7] = jb_17;
        tablero[2][0] = jb_20;
        tablero[2][1] = jb_21;
        tablero[2][2] = jb_22;
        tablero[2][3] = jb_23;
        tablero[2][4] = jb_24;
        tablero[2][5] = jb_25;
        tablero[2][6] = jb_26;
        tablero[2][7] = jb_27;
        tablero[3][0] = jb_30;
        tablero[3][1] = jb_31;
        tablero[3][2] = jb_32;
        tablero[3][3] = jb_33;
        tablero[3][4] = jb_34;
        tablero[3][5] = jb_35;
        tablero[3][6] = jb_36;
        tablero[3][7] = jb_37;
        tablero[4][0] = jb_40;
        tablero[4][1] = jb_41;
        tablero[4][2] = jb_42;
        tablero[4][3] = jb_43;
        tablero[4][4] = jb_44;
        tablero[4][5] = jb_45;
        tablero[4][6] = jb_46;
        tablero[4][7] = jb_47;
        tablero[5][0] = jb_50;
        tablero[5][1] = jb_51;
        tablero[5][2] = jb_52;
        tablero[5][3] = jb_53;
        tablero[5][4] = jb_54;
        tablero[5][5] = jb_55;
        tablero[5][6] = jb_56;
        tablero[5][7] = jb_57;
        tablero[6][0] = jb_60;
        tablero[6][1] = jb_61;
        tablero[6][2] = jb_62;
        tablero[6][3] = jb_63;
        tablero[6][4] = jb_64;
        tablero[6][5] = jb_65;
        tablero[6][6] = jb_66;
        tablero[6][7] = jb_67;
        tablero[7][0] = jb_70;
        tablero[7][1] = jb_71;
        tablero[7][2] = jb_72;
        tablero[7][3] = jb_73;
        tablero[7][4] = jb_74;
        tablero[7][5] = jb_75;
        tablero[7][6] = jb_76;
        tablero[7][7] = jb_77;
        llenarTableroString(tableroString);
        tableroDefecto(0, 0);
        jl_turno.setText("BLANCO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_00 = new javax.swing.JButton();
        jb_01 = new javax.swing.JButton();
        jb_10 = new javax.swing.JButton();
        jb_11 = new javax.swing.JButton();
        jb_20 = new javax.swing.JButton();
        jb_21 = new javax.swing.JButton();
        jb_30 = new javax.swing.JButton();
        jb_31 = new javax.swing.JButton();
        jb_12 = new javax.swing.JButton();
        jb_02 = new javax.swing.JButton();
        jb_13 = new javax.swing.JButton();
        jb_03 = new javax.swing.JButton();
        jb_32 = new javax.swing.JButton();
        jb_22 = new javax.swing.JButton();
        jb_33 = new javax.swing.JButton();
        jb_23 = new javax.swing.JButton();
        jb_27 = new javax.swing.JButton();
        jb_37 = new javax.swing.JButton();
        jb_36 = new javax.swing.JButton();
        jb_26 = new javax.swing.JButton();
        jb_04 = new javax.swing.JButton();
        jb_05 = new javax.swing.JButton();
        jb_06 = new javax.swing.JButton();
        jb_07 = new javax.swing.JButton();
        jb_17 = new javax.swing.JButton();
        jb_16 = new javax.swing.JButton();
        jb_15 = new javax.swing.JButton();
        jb_14 = new javax.swing.JButton();
        jb_24 = new javax.swing.JButton();
        jb_34 = new javax.swing.JButton();
        jb_35 = new javax.swing.JButton();
        jb_25 = new javax.swing.JButton();
        jb_70 = new javax.swing.JButton();
        jb_43 = new javax.swing.JButton();
        jb_52 = new javax.swing.JButton();
        jb_71 = new javax.swing.JButton();
        jb_40 = new javax.swing.JButton();
        jb_63 = new javax.swing.JButton();
        jb_72 = new javax.swing.JButton();
        jb_60 = new javax.swing.JButton();
        jb_53 = new javax.swing.JButton();
        jb_62 = new javax.swing.JButton();
        jb_51 = new javax.swing.JButton();
        jb_61 = new javax.swing.JButton();
        jb_42 = new javax.swing.JButton();
        jb_50 = new javax.swing.JButton();
        jb_73 = new javax.swing.JButton();
        jb_41 = new javax.swing.JButton();
        jb_55 = new javax.swing.JButton();
        jb_64 = new javax.swing.JButton();
        jb_54 = new javax.swing.JButton();
        jb_47 = new javax.swing.JButton();
        jb_76 = new javax.swing.JButton();
        jb_44 = new javax.swing.JButton();
        jb_65 = new javax.swing.JButton();
        jb_46 = new javax.swing.JButton();
        jb_66 = new javax.swing.JButton();
        jb_45 = new javax.swing.JButton();
        jb_74 = new javax.swing.JButton();
        jb_56 = new javax.swing.JButton();
        jb_67 = new javax.swing.JButton();
        jb_57 = new javax.swing.JButton();
        jb_77 = new javax.swing.JButton();
        jb_75 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jl_turno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 244, 163));
        jPanel1.setPreferredSize(new java.awt.Dimension(693, 771));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_00.setBackground(new java.awt.Color(255, 244, 163));
        jb_00.setName("0,0"); // NOI18N
        jb_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_00, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 31, 70, 70));

        jb_01.setBackground(new java.awt.Color(134, 55, 13));
        jb_01.setName("0,1"); // NOI18N
        jb_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 31, 70, 70));

        jb_10.setBackground(new java.awt.Color(134, 55, 13));
        jb_10.setName("1,0"); // NOI18N
        jb_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 95, 70, 70));

        jb_11.setBackground(new java.awt.Color(255, 244, 163));
        jb_11.setName("1,1"); // NOI18N
        jb_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 95, 70, 70));

        jb_20.setBackground(new java.awt.Color(255, 244, 163));
        jb_20.setName("2,0"); // NOI18N
        jb_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 159, 70, 70));

        jb_21.setBackground(new java.awt.Color(134, 55, 13));
        jb_21.setName("2,1"); // NOI18N
        jb_21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 159, 70, 70));

        jb_30.setBackground(new java.awt.Color(134, 55, 13));
        jb_30.setName("3,0"); // NOI18N
        jb_30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 223, 70, 70));

        jb_31.setBackground(new java.awt.Color(255, 244, 163));
        jb_31.setName("3,1"); // NOI18N
        jb_31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 223, 70, 70));

        jb_12.setBackground(new java.awt.Color(134, 55, 13));
        jb_12.setName("1,2"); // NOI18N
        jb_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 95, 70, 70));

        jb_02.setBackground(new java.awt.Color(255, 244, 163));
        jb_02.setName("0,2"); // NOI18N
        jb_02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 31, 70, 70));

        jb_13.setBackground(new java.awt.Color(255, 244, 163));
        jb_13.setName("1,3"); // NOI18N
        jb_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 95, 70, 70));

        jb_03.setBackground(new java.awt.Color(134, 55, 13));
        jb_03.setName("0,3"); // NOI18N
        jb_03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_03, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 31, 70, 70));

        jb_32.setBackground(new java.awt.Color(134, 55, 13));
        jb_32.setName("3,2"); // NOI18N
        jb_32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 223, 70, 70));

        jb_22.setBackground(new java.awt.Color(255, 244, 163));
        jb_22.setName("2,2"); // NOI18N
        jb_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 159, 70, 70));

        jb_33.setBackground(new java.awt.Color(255, 244, 163));
        jb_33.setName("3,3"); // NOI18N
        jb_33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 223, 70, 70));

        jb_23.setBackground(new java.awt.Color(134, 55, 13));
        jb_23.setName("2,3"); // NOI18N
        jb_23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 159, 70, 70));

        jb_27.setBackground(new java.awt.Color(134, 55, 13));
        jb_27.setName("2,7"); // NOI18N
        jb_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 159, 70, 70));

        jb_37.setBackground(new java.awt.Color(255, 244, 163));
        jb_37.setName("3,7"); // NOI18N
        jb_37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 223, 70, 70));

        jb_36.setBackground(new java.awt.Color(134, 55, 13));
        jb_36.setName("3,6"); // NOI18N
        jb_36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 223, 70, 70));

        jb_26.setBackground(new java.awt.Color(255, 244, 163));
        jb_26.setName("2,6"); // NOI18N
        jb_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 159, 70, 70));

        jb_04.setBackground(new java.awt.Color(255, 244, 163));
        jb_04.setName("0,4"); // NOI18N
        jb_04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_04, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 31, 70, 70));

        jb_05.setBackground(new java.awt.Color(134, 55, 13));
        jb_05.setName("0,5"); // NOI18N
        jb_05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_05, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 31, 70, 70));

        jb_06.setBackground(new java.awt.Color(255, 244, 163));
        jb_06.setName("0,6"); // NOI18N
        jb_06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_06, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 31, 70, 70));

        jb_07.setBackground(new java.awt.Color(134, 55, 13));
        jb_07.setName("0,7"); // NOI18N
        jb_07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_07, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 31, 70, 70));

        jb_17.setBackground(new java.awt.Color(255, 244, 163));
        jb_17.setName("1,7"); // NOI18N
        jb_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 95, 70, 70));

        jb_16.setBackground(new java.awt.Color(134, 55, 13));
        jb_16.setName("1,6"); // NOI18N
        jb_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 95, 70, 70));

        jb_15.setBackground(new java.awt.Color(255, 244, 163));
        jb_15.setName("1,5"); // NOI18N
        jb_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 95, 70, 70));

        jb_14.setBackground(new java.awt.Color(134, 55, 13));
        jb_14.setName("1,4"); // NOI18N
        jb_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 95, 70, 70));

        jb_24.setBackground(new java.awt.Color(255, 244, 163));
        jb_24.setName("2,4"); // NOI18N
        jb_24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 159, 70, 70));

        jb_34.setBackground(new java.awt.Color(134, 55, 13));
        jb_34.setName("3,4"); // NOI18N
        jb_34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 223, 70, 70));

        jb_35.setBackground(new java.awt.Color(255, 244, 163));
        jb_35.setName("3,5"); // NOI18N
        jb_35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 223, 70, 70));

        jb_25.setBackground(new java.awt.Color(134, 55, 13));
        jb_25.setName("2,5"); // NOI18N
        jb_25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 159, 70, 70));

        jb_70.setBackground(new java.awt.Color(134, 55, 13));
        jb_70.setName("7,0"); // NOI18N
        jb_70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_70, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 479, 70, 70));

        jb_43.setBackground(new java.awt.Color(134, 55, 13));
        jb_43.setName("4,3"); // NOI18N
        jb_43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_43, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 287, 70, 70));

        jb_52.setBackground(new java.awt.Color(134, 55, 13));
        jb_52.setName("5,2"); // NOI18N
        jb_52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_52, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 351, 70, 70));

        jb_71.setBackground(new java.awt.Color(255, 244, 163));
        jb_71.setName("7,1"); // NOI18N
        jb_71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_71, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 479, 70, 70));

        jb_40.setBackground(new java.awt.Color(255, 244, 163));
        jb_40.setName("4,0"); // NOI18N
        jb_40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 287, 70, 70));

        jb_63.setBackground(new java.awt.Color(134, 55, 13));
        jb_63.setName("6,3"); // NOI18N
        jb_63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_63, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 415, 70, 70));

        jb_72.setBackground(new java.awt.Color(134, 55, 13));
        jb_72.setName("7,2"); // NOI18N
        jb_72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_72, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 479, 70, 70));

        jb_60.setBackground(new java.awt.Color(255, 244, 163));
        jb_60.setName("6,0"); // NOI18N
        jb_60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_60, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 415, 70, 70));

        jb_53.setBackground(new java.awt.Color(255, 244, 163));
        jb_53.setName("5,3"); // NOI18N
        jb_53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_53, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 351, 70, 70));

        jb_62.setBackground(new java.awt.Color(255, 244, 163));
        jb_62.setName("6,2"); // NOI18N
        jb_62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_62, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 415, 70, 70));

        jb_51.setBackground(new java.awt.Color(255, 244, 163));
        jb_51.setName("5,1"); // NOI18N
        jb_51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_51, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 351, 70, 70));

        jb_61.setBackground(new java.awt.Color(134, 55, 13));
        jb_61.setName("6,1"); // NOI18N
        jb_61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_61, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 415, 70, 70));

        jb_42.setBackground(new java.awt.Color(255, 244, 163));
        jb_42.setName("4,2"); // NOI18N
        jb_42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_42, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 287, 70, 70));

        jb_50.setBackground(new java.awt.Color(134, 55, 13));
        jb_50.setName("5,0"); // NOI18N
        jb_50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_50, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 351, 70, 70));

        jb_73.setBackground(new java.awt.Color(255, 244, 163));
        jb_73.setName("7,3"); // NOI18N
        jb_73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_73, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 479, 70, 70));

        jb_41.setBackground(new java.awt.Color(134, 55, 13));
        jb_41.setName("4,1"); // NOI18N
        jb_41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_41, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 287, 70, 70));

        jb_55.setBackground(new java.awt.Color(255, 244, 163));
        jb_55.setName("5,5"); // NOI18N
        jb_55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_55, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 351, 70, 70));

        jb_64.setBackground(new java.awt.Color(255, 244, 163));
        jb_64.setName("6,4"); // NOI18N
        jb_64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_64, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 415, 70, 70));

        jb_54.setBackground(new java.awt.Color(134, 55, 13));
        jb_54.setName("5,4"); // NOI18N
        jb_54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_54, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 351, 70, 70));

        jb_47.setBackground(new java.awt.Color(134, 55, 13));
        jb_47.setName("4,7"); // NOI18N
        jb_47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_47, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 287, 70, 70));

        jb_76.setBackground(new java.awt.Color(134, 55, 13));
        jb_76.setName("7,6"); // NOI18N
        jb_76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_76, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 479, 70, 70));

        jb_44.setBackground(new java.awt.Color(255, 244, 163));
        jb_44.setName("4,4"); // NOI18N
        jb_44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_44, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 287, 70, 70));

        jb_65.setBackground(new java.awt.Color(134, 55, 13));
        jb_65.setName("6,5"); // NOI18N
        jb_65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_65, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 415, 70, 70));

        jb_46.setBackground(new java.awt.Color(255, 244, 163));
        jb_46.setName("4,6"); // NOI18N
        jb_46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_46, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 287, 70, 70));

        jb_66.setBackground(new java.awt.Color(255, 244, 163));
        jb_66.setName("6,6"); // NOI18N
        jb_66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_66, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 415, 70, 70));

        jb_45.setBackground(new java.awt.Color(134, 55, 13));
        jb_45.setName("4,5"); // NOI18N
        jb_45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_45, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 287, 70, 70));

        jb_74.setBackground(new java.awt.Color(134, 55, 13));
        jb_74.setName("7,4"); // NOI18N
        jb_74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_74, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 479, 70, 70));

        jb_56.setBackground(new java.awt.Color(134, 55, 13));
        jb_56.setName("5,6"); // NOI18N
        jb_56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_56, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 351, 70, 70));

        jb_67.setBackground(new java.awt.Color(134, 55, 13));
        jb_67.setName("6,7"); // NOI18N
        jb_67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_67, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 415, 70, 70));

        jb_57.setBackground(new java.awt.Color(255, 244, 163));
        jb_57.setName("5,7"); // NOI18N
        jb_57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_57, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 351, 70, 70));

        jb_77.setBackground(new java.awt.Color(255, 244, 163));
        jb_77.setName("7,7"); // NOI18N
        jb_77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_77, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 479, 70, 70));

        jb_75.setBackground(new java.awt.Color(255, 244, 163));
        jb_75.setName("7,5"); // NOI18N
        jb_75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mover(evt);
            }
        });
        jPanel1.add(jb_75, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 479, 70, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TURNO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

        jl_turno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jl_turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mover
        // TODO add your handling code here:
        if (((JButton) evt.getComponent()).getIcon() != null && tipoPieza((JButton) evt.getComponent()).getJugador() == turno && flag == 0) {
            posActual = (JButton) evt.getComponent();
            flag++;
        }
        if (((JButton) evt.getComponent()) != posActual && flag > 0 && (((JButton) evt.getComponent()).getIcon() == null
                || tipoPieza(posActual).getJugador() != tipoPieza((JButton) evt.getComponent()).getJugador())) {
            posDestino = (JButton) evt.getComponent();
            flag = 0;
            if (tipoPieza(posActual).movimiento(posActual, posDestino, tableroString, turno)) {
                String pieza = tableroString[coordenada("fila", posActual)][coordenada("col", posActual)];
                tableroString[coordenada("fila", posActual)][coordenada("col", posActual)] = " ";
                tableroString[coordenada("fila", posDestino)][coordenada("col", posDestino)] = pieza;
                posDestino.setIcon(posActual.getIcon());
                posActual.setIcon(null);
                if (turno == 1) {
                    jl_turno.setText("NEGRO");
                    turno = 2;
                } else {
                    jl_turno.setText("BLANCO");
                    turno = 1;
                }
            }
        }
    }//GEN-LAST:event_mover

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    //Método Recursivo
    public void tableroDefecto(int fila, int columna) {
        if (fila < 8) {
            if (columna < 8) {
                if (fila == 1) {
                    tablero[fila][columna].setIcon(peon2.getImagen());
                    tableroString[fila][columna] = "peon2";
                }
                if (fila == 6) {
                    tablero[fila][columna].setIcon(peon1.getImagen());
                    tableroString[fila][columna] = "peon1";
                }
                if (fila == 0 && (columna == 0 || columna == 7)) {
                    tablero[fila][columna].setIcon(torre2.getImagen());
                    tableroString[fila][columna] = "torre2";
                }
                if (fila == 7 && (columna == 0 || columna == 7)) {
                    tablero[fila][columna].setIcon(torre1.getImagen());
                    tableroString[fila][columna] = "torre1";
                }
                if (fila == 0 && (columna == 1 || columna == 6)) {
                    tablero[fila][columna].setIcon(caballo2.getImagen());
                    tableroString[fila][columna] = "caballo2";
                }
                if (fila == 7 && (columna == 1 || columna == 6)) {
                    tablero[fila][columna].setIcon(caballo1.getImagen());
                    tableroString[fila][columna] = "caballo1";
                }
                if (fila == 0 && (columna == 2 || columna == 5)) {
                    tablero[fila][columna].setIcon(alfil2.getImagen());
                    tableroString[fila][columna] = "alfil2";
                }
                if (fila == 7 && (columna == 2 || columna == 5)) {
                    tablero[fila][columna].setIcon(alfil1.getImagen());
                    tableroString[fila][columna] = "alfil1";
                }

                if (fila == 0 && columna == 3) {
                    tablero[fila][columna].setIcon(rey2.getImagen());
                    tableroString[fila][columna] = "rey2";
                }
                if (fila == 7 && columna == 3) {
                    tablero[fila][columna].setIcon(rey1.getImagen());
                    tableroString[fila][columna] = "rey1";
                }

                if (fila == 0 && columna == 4) {
                    tablero[fila][columna].setIcon(reina2.getImagen());
                    tableroString[fila][columna] = "reina2";
                }
                if (fila == 7 && columna == 4) {
                    tablero[fila][columna].setIcon(reina1.getImagen());
                    tableroString[fila][columna] = "reina1";
                }
                columna++;
                tableroDefecto(fila, columna);
            } else {
                columna = 0;
                fila++;
                tableroDefecto(fila, columna);
            }
        }
    }

    public void llenarTableroString(String[][] tablero) {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                tablero[i][j] = " ";
            }
        }
    }

    public Pieza tipoPieza(JButton casilla) {
        if (casilla.getIcon() == peon1.getImagen()) {
            return peon1;
        } else if (casilla.getIcon() == alfil1.getImagen()) {
            return alfil1;
        } else if (casilla.getIcon() == alfil2.getImagen()) {
            return alfil2;
        } else if (casilla.getIcon() == peon2.getImagen()) {
            return peon2;
        } else if (casilla.getIcon() == caballo1.getImagen()) {
            return caballo1;
        } else if (casilla.getIcon() == caballo2.getImagen()) {
            return caballo2;
        } else if (casilla.getIcon() == torre1.getImagen()) {
            return torre1;
        } else if (casilla.getIcon() == torre2.getImagen()) {
            return torre2;
        } else if (casilla.getIcon() == rey1.getImagen()) {
            return rey1;
        } else if (casilla.getIcon() == rey2.getImagen()) {
            return rey2;
        } else if (casilla.getIcon() == reina1.getImagen()) {
            return reina1;
        } else if (casilla.getIcon() == reina2.getImagen()) {
            return reina2;
        } else {
            return null;
        }
    }

    public int coordenada(String indicador, JButton boton) {
        String coordenadas = boton.getName();
        int fila = Integer.parseInt(String.valueOf(coordenadas.charAt(0)));
        int columna = Integer.parseInt(String.valueOf(coordenadas.charAt(2)));
        if (indicador.equalsIgnoreCase("fila")) {
            return fila;
        } else {
            return columna;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_00;
    private javax.swing.JButton jb_01;
    private javax.swing.JButton jb_02;
    private javax.swing.JButton jb_03;
    private javax.swing.JButton jb_04;
    private javax.swing.JButton jb_05;
    private javax.swing.JButton jb_06;
    private javax.swing.JButton jb_07;
    private javax.swing.JButton jb_10;
    private javax.swing.JButton jb_11;
    private javax.swing.JButton jb_12;
    private javax.swing.JButton jb_13;
    private javax.swing.JButton jb_14;
    private javax.swing.JButton jb_15;
    private javax.swing.JButton jb_16;
    private javax.swing.JButton jb_17;
    private javax.swing.JButton jb_20;
    private javax.swing.JButton jb_21;
    private javax.swing.JButton jb_22;
    private javax.swing.JButton jb_23;
    private javax.swing.JButton jb_24;
    private javax.swing.JButton jb_25;
    private javax.swing.JButton jb_26;
    private javax.swing.JButton jb_27;
    private javax.swing.JButton jb_30;
    private javax.swing.JButton jb_31;
    private javax.swing.JButton jb_32;
    private javax.swing.JButton jb_33;
    private javax.swing.JButton jb_34;
    private javax.swing.JButton jb_35;
    private javax.swing.JButton jb_36;
    private javax.swing.JButton jb_37;
    private javax.swing.JButton jb_40;
    private javax.swing.JButton jb_41;
    private javax.swing.JButton jb_42;
    private javax.swing.JButton jb_43;
    private javax.swing.JButton jb_44;
    private javax.swing.JButton jb_45;
    private javax.swing.JButton jb_46;
    private javax.swing.JButton jb_47;
    private javax.swing.JButton jb_50;
    private javax.swing.JButton jb_51;
    private javax.swing.JButton jb_52;
    private javax.swing.JButton jb_53;
    private javax.swing.JButton jb_54;
    private javax.swing.JButton jb_55;
    private javax.swing.JButton jb_56;
    private javax.swing.JButton jb_57;
    private javax.swing.JButton jb_60;
    private javax.swing.JButton jb_61;
    private javax.swing.JButton jb_62;
    private javax.swing.JButton jb_63;
    private javax.swing.JButton jb_64;
    private javax.swing.JButton jb_65;
    private javax.swing.JButton jb_66;
    private javax.swing.JButton jb_67;
    private javax.swing.JButton jb_70;
    private javax.swing.JButton jb_71;
    private javax.swing.JButton jb_72;
    private javax.swing.JButton jb_73;
    private javax.swing.JButton jb_74;
    private javax.swing.JButton jb_75;
    private javax.swing.JButton jb_76;
    private javax.swing.JButton jb_77;
    private javax.swing.JLabel jl_turno;
    // End of variables declaration//GEN-END:variables
}
